#ifndef _COMMONDEFINES_H_
#define _COMMONDEFINES_H_

#define EPISODE_TOTAL_DAYS 59
#define EPISODE_TOTAL_TIME (EPISODE_TOTAL_DAYS*24*60*60)
#define EPISODE_OVERSIGHT_BILLING_MINUTES 30


#define EPISODE_BILLING_STATUS_NA			0
#define EPISODE_BILLING_STATUS_INITIAL		1
#define EPISODE_BILLING_STATUS_OVERSIGHT	2
#define EPISODE_BILLING_STATUS_OVERSIGHT2	3

#define EPISODE_BILLING_DAYS		30



#endif