//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HomeHealth.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MDFMDIAPP_FORM              101
#define IDS_STRING_DATABASE_PATH        101
#define IDS_STRING_HOMEHEALTH_DATABASE  102
#define IDP_FAILED_OPEN_DATABASE        103
#define AFX_IDS_ADD_PATIENT_CONFIRMATION 104
#define AFX_IDS_PATIENT_EDIT_CONFIRM    105
#define IDS_TITLE_NAME                  106
#define IDS_TITLE_BILL                  107
#define IDS_DOCTOR_DEPT                 108
#define IDS_DOCTOR_ADDR1                109
#define IDS_DOCTOR_ADDR2                110
#define IDS_DOCTOR_PHONE                111
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_PATIENT_MASTER_ERROR        126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MDFMDIAppTYPE               130
#define ID_WINDOW_MANAGER               131
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_PATIENT_OPEN         310
#define IDD_DIALOG_OVERSIGHT_BILLING    311
#define IDD_DIALOG_OVERSIGHT_RECORD     311
#define IDD_EPISODE_ADD                 313
#define IDR_EPISODE_CONTEXT             315
#define IDD_ADD_PATIENT                 316
#define IDB_BITMAP_RED_LIGHT            323
#define IDB_BITMAP_YELLOW_LIGHT         324
#define IDB_BITMAP_GREEN_SMALL          328
#define IDB_BITMAP_RED_SMALL            329
#define IDB_BITMAP_YELLOW_SMALL         330
#define IDD_INIT_BILLING                332
#define IDD_OVERSIGHT_BILLING           333
#define IDC_PATIENT_EPISODE             1001
#define IDC_LIST_PATIENT_SEARCH         1001
#define IDC_DXCODES_LIST                1001
#define IDC_EDIT_FIRSTNAME              1002
#define IDC_EDIT_LASTNAME               1003
#define IDC_BUTTON_MORE_SEARCH          1004
#define IDC_BUTTON_SEARCH               1005
#define IDC_LIST_PATIENT_LISTCTRL       1006
#define IDC_LIST_PATIENT                1007
#define IDC_EDIT_PATIENT_ADDR           1009
#define IDC_PAT_ADD_MIDDLE_NAME         1009
#define IDC_DXCODES                     1009
#define IDC_EDIT_PATIENT_STATE          1010
#define IDC_EDIT_EPISODEID              1010
#define IDC_PAT_ADD_FIRST_NAME          1010
#define IDC_COUNTRY                     1010
#define IDC_EDIT_PATIENT_NAME           1011
#define IDC_EDIT_EPISODE_DATE           1011
#define IDC_PAT_ADD_STREET              1011
#define IDC_EDIT_PATIENT_LASTNAME       1011
#define IDC_EDIT_EPISODE_START_DATE     1011
#define IDC_EDIT_TOTAL_MINS             1012
#define IDC_EDIT_OVERSIGHT_MINS         1012
#define IDC_PAT_ADD_APT                 1012
#define IDC_EDIT6                       1013
#define IDC_EDIT_PATIENT_TOWN           1013
#define IDC_EDIT_INSTRUCTION            1013
#define IDC_PAT_ADD_TOWN                1013
#define IDC_EDIT_DIAGNOSIS              1013
#define IDC_EDIT7                       1014
#define IDC_EDIT_PATIENT_ID             1014
#define IDC_PAT_ADD_COUNTRY             1014
#define IDC_EDIT_EPISODE_END_DATE       1014
#define IDC_EDIT_WORK_PHONE             1015
#define IDC_LIST_OVERSIGHT              1016
#define IDC_BUTTON_ADD_EPISODE          1017
#define IDC_BUTTON_ADD_OVERSIGHT        1018
#define IDC_BUTTON_OVERSIGHT_HEALTH     1019
#define IDC_BUTTON4                     1020
#define IDC_EDIT_HOME_PHONE             1020
#define IDC_BUTTON5                     1021
#define IDC_DATETIME_OVERSIGHT          1023
#define IDC_CHECK_CHARTS                1024
#define IDC_CHECK_MEDICINE              1025
#define IDC_CHECK_STUDIES               1026
#define IDC_CHECK_APPOINTMENT           1027
#define IDC_DATETIME_NEXT_APPOINTMENT   1028
#define IDC_DATETIME_APPOINTMENT_TIME   1029
#define IDC_COMBO_CPO_CODE              1030
#define IDC_PATIENT_NAME                1031
#define IDC_EPISODE_START               1032
#define IDC_EPISODEEND                  1033
#define IDC_COMBO1                      1034
#define IDC_COMBO_EPISODE_TYPE          1034
#define IDC_PAT_ADD_SALUTATION          1034
#define IDC_COMBO_STATE                 1034
#define IDC_PAT_ADD_LAST_NAME           1035
#define IDC_PAT_ADD_STATE               1036
#define IDC_PAT_ADD_WORK_PHONE          1037
#define IDC_PAT_ADD_COMMUNICATION_PHONE 1038
#define IDC_PAT_ADD_CELL_PHONE          1039
#define IDC_PAT_ADD_HOME_PHONE          1040
#define IDC_EDIT_PAT_MIDDLE_NAME        1041
#define IDC_PATIENT_FIRST_NAME          1042
#define IDC_EDIT_APARTMENT              1043
#define IDC_COMBO_TITLE                 1044
#define IDC_EDIT_CELL_PHONE             1045
#define IDC_PATIENT_REGISTRATION        1048
#define IDC_PATIENT_LAST_VISIT          1049
#define IDC_PATIENT_LAST_BILL           1050
#define IDC_PATIENT_ZIP                 1051
#define IDC_DATETIMEPATIENTDOB          1052
#define IDC_COMBO_HHAGENCY              1055
#define IDC_CPO_CODE_DESCR              1056
#define IDC_BITMAP_GREEN_LIGHT          1057
#define IDC_BUTTON_BILL_CONTROL         1059
#define IDC_BUTTONBill                  1060
#define IDC_HHAGENCY                    1061
#define IDC_PATIENTNAME                 1062
#define IDC_EOS_FROM                    1063
#define IDC_EOS_TO                      1064
#define IDC_DOCTOR_NAME                 1065
#define IDC_DOCTOR_DEPT                 1066
#define IDC_DOCTOR_ADDR                 1067
#define IDC_DOCTOR_TOWN                 1068
#define IDC_DOCTOR_PHONE                1069
#define IDC_HH_AGENCY                   1070
#define IDC_OVERSIGHT_LIST              1071
#define IDC_BILL_DATE                   1072
#define IDC_TOTAL_MINS                  1073
#define IDC_LIST1                       1073
#define IDC_BILL_LIST                   1073
#define IDC_DIAGNOSIS                   1074
#define IDC_NAME                        1075
#define IDC_SEX                         1075
#define IDC_COMBO_SEX                   1075
#define IDC_DOB                         1076
#define IDC_ACTIVITY                    1077
#define IDC_EOS                         1078
#define IDC_LAST_SEEN                   1079
#define IDC_DATE                        1080
#define IDC_MONTH                       1080
#define ID_EPISODE_EDIT                 32771
#define ID_EPISODE_DELETE               32772
#define ID_EPISODE_EDIT32773            32773
#define ID_EPISODE_DELETE32774          32774
#define ID_EPISODE_ADD                  32775
#define ID_OVERSIGHT_HEALTHDATA         32776
#define ID_OVERSIGHT_ADD                32777
#define ID_OVERSIGHT_EDIT               32778
#define ID_OVERSIGHT_DELETE             32779
#define ID_REPORTS_BILLING30MINUTES     32780
#define ID_REPORTS_PATIENTLEDGER        32781
#define ID_REPORTS_TODAY                32782
#define ID_REPORTS_PATIENTLEDGER32783   32783
#define ID_REPORTS_TODAY32784           32784
#define ID_REPORTS_PATIENTLEDGER32785   32785
#define ID_REPORTS_TODAY32786           32786
#define ID_REPORTS_TODAY32787           32787
#define ID_REPORT_BILLING_30MINS        32788
#define ID_REPORT_TODAYS_APT            32789
#define ID_TIMEPAAS_NOWDOTHEWORK        32790
#define ID_EPISODE_ADDOVERSIGHT         32791
#define ID_EPISODE_ADDOVERSIGHT32792    32792
#define ID_OVERSIGHT_SEPERATOR          32793
#define ID_PATIENT_SWITCH               32794
#define ID_VIEW_SWITCH                  32795
#define ID_VIEW_SWITCH32796             32796
#define ID_PRINTED_BILL                 58586

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        335
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
